# Generated by Django 5.0.7 on 2024-08-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
    ]
