# Generated by Django 5.0.7 on 2024-07-26 06:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_detail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
