# Generated by Django 5.0.7 on 2024-07-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_detail_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='id',
            new_name='uuid',
        ),
    ]
