# Generated by Django 5.0.7 on 2024-07-29 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_body_detail_variant_detail_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='body_detail',
            name='detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.detail'),
        ),
    ]
