# Generated by Django 5.0.7 on 2024-08-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_detail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='static/images/'),
        ),
    ]
