# Generated by Django 5.0.7 on 2024-08-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_detail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='source_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
