# Generated by Django 5.0.7 on 2024-09-23 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_detail_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'ordering': ['-created']},
        ),
        migrations.DeleteModel(
            name='Body_detail',
        ),
    ]
